"""create_system_health_snapshots

Revision ID: 6230b6ae8610
Revises: 7af1e0d9a61b
Create Date: 2026-05-16 23:37:45.176613

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6230b6ae8610'
down_revision = '7af1e0d9a61b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_health_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('overall_status', sa.String(length=32), nullable=False),
    sa.Column('queue_depth', sa.Integer(), nullable=False),
    sa.Column('active_workers', sa.Integer(), nullable=False),
    sa.Column('retry_rate', sa.Float(), nullable=True),
    sa.Column('failed_task_rate', sa.Float(), nullable=True),
    sa.Column('avg_processing_duration', sa.Float(), nullable=True),
    sa.Column('avg_recognition_duration', sa.Float(), nullable=True),
    sa.Column('critical_events_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_health_snapshots_created_at'), 'system_health_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_health_snapshots_overall_status'), 'system_health_snapshots', ['overall_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_health_snapshots_overall_status'), table_name='system_health_snapshots')
    op.drop_index(op.f('ix_system_health_snapshots_created_at'), table_name='system_health_snapshots')
    op.drop_table('system_health_snapshots')
    # ### end Alembic commands ###
