"""create_incident_snapshots

Revision ID: 7af1e0d9a61b
Revises: ddd9f6227c15
Create Date: 2026-05-16 23:26:13.706497

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7af1e0d9a61b'
down_revision = 'ddd9f6227c15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('student_id', sa.String(length=255), nullable=True),
    sa.Column('traceback_summary', sa.Text(), nullable=False),
    sa.Column('processing_context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('request_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('task_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_snapshots_correlation_id'), 'incident_snapshots', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_incident_snapshots_request_id'), 'incident_snapshots', ['request_id'], unique=False)
    op.create_index(op.f('ix_incident_snapshots_student_id'), 'incident_snapshots', ['student_id'], unique=False)
    op.create_index(op.f('ix_incident_snapshots_task_id'), 'incident_snapshots', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_snapshots_task_id'), table_name='incident_snapshots')
    op.drop_index(op.f('ix_incident_snapshots_student_id'), table_name='incident_snapshots')
    op.drop_index(op.f('ix_incident_snapshots_request_id'), table_name='incident_snapshots')
    op.drop_index(op.f('ix_incident_snapshots_correlation_id'), table_name='incident_snapshots')
    op.drop_table('incident_snapshots')
    # ### end Alembic commands ###
