"""add_tracing_correlation_ids

Revision ID: ddd9f6227c15
Revises: 20260516_0009
Create Date: 2026-05-16 23:25:27.924176

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd9f6227c15'
down_revision = '20260516_0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('request_id', sa.String(length=128), nullable=True))
    op.add_column('audit_logs', sa.Column('correlation_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.add_column('biometric_tasks', sa.Column('request_id', sa.String(length=128), nullable=True))
    op.add_column('biometric_tasks', sa.Column('correlation_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_biometric_tasks_correlation_id'), 'biometric_tasks', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_biometric_tasks_request_id'), 'biometric_tasks', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biometric_tasks_request_id'), table_name='biometric_tasks')
    op.drop_index(op.f('ix_biometric_tasks_correlation_id'), table_name='biometric_tasks')
    op.drop_column('biometric_tasks', 'correlation_id')
    op.drop_column('biometric_tasks', 'request_id')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'correlation_id')
    op.drop_column('audit_logs', 'request_id')
    # ### end Alembic commands ###
